name: Start npm start

on:
  push:
    branches:
      - main

jobs:
  start-npm-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Start npm start
        env:
          NODE_ENV: development
        run: |
          npm start
